### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mark-kubacki** [Blitznote/docker-ubuntu-debootstrap#9]
- [x] Use label `blitznote/debase` on the Docker hub.  
It will be a multi-arch "image," referencing this one for now.
- [x] Publish images for ~~32b and~~ 64b *aarch*.
- [x] Split the documentation into distinct files.  
The current one-file README is an unfocused collection of notes.
- [x] In light of Docker's multi-stage *image build* process (kind of similar to how I build `ci-php`) publish an absolutely minimal image, without *curl* and *decompressors*.

**Comment by mark-kubacki** [comment]
I've procured an `arm64` (`armv8`, *Cavium ThunderX*) machine. Anything other than `aarch64`, especially 32b ARM, will not be targeted. Images for ARM are scheduled right behind recompiling of some binaries due to the recently discovered flaws in (especially Intel) cpus.

**Comment by mark-kubacki** [comment]
Done. Closing because the results will be pushed and published come Feb.
